// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig, env } from 'prisma/config';

export default defineConfig({
  schema: 'lib/prisma/schema.prisma',
  migrations: {
    path: 'lib/prisma/migrations',
  },
  datasource: {
    url: env('DIRECT_URL'), // migrations에는 direct connection 사용
  },
});
